### ISSUE TITLE
Guest checkout plans?

### ISSUE THREAD

**Issue by restyler** [Sylius/Sylius-Sandbox#66]
Hi. Do you have plans to implement checkout for anonymous users?

**Comment by pjedrzejewski** [comment]
Yes, I have an idea how to implement it, I will keep you updated.

**Comment by whisller** [comment]
http://www.prestashop.com/forums/topic/173207-why-you-should-avoid-enabling-guest-checkout/
http://www.pandadoodle.com/blog/guest-checkout-yes-or-no-prestashop/ - here guy said maybe instead of using "guest checkout" which in fact is a complicated for a developers and for a whole flow, use one of the existing oauth.

**Comment by pjedrzejewski** [comment]
@whisller Thanks for those links, interesting. Seems like we have to rethink if we really want to support this. :)
